# Channels and how they should be colocalised 
channels: 
  PSD: 
    ALZ50: overlap
    SY38: distance
  SY38: 
    PSD: distance
    ALZ50: overlap
  ALZ50:
    PSD: overlap
    SY38: overlap

# Name of output csv file
csv_name: test_1.csv

# Resolutions etc.
xy_resolution: 0.102
z_resolution: 0.07
min_overlap: 0.25
max_distance: 0.5