# Channels and how they should be colocalised 
channels: 
  PSD: 
    ALZ50: overlap
    SY38: overlap
    Tau: overlap
  SY38: 
    PSD: overlap
    ALZ50: overlap
    Tau: overlap
  ALZ50:
    PSD: overlap
    SY38: overlap
    Tau: overlap
  Tau:
    PSD: overlap
    SY38: overlap
    ALZ50: overlap


# Name of output csv file
csv_name: 4chanl_test.csv

# Resolutions etc.
xy_resolution: 0.102
z_resolution: 0.07
min_overlap: 0.25
max_distance: 0.5