name: CI


on:
  push:
    tags:
    - '*'
    paths:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: jerray/publish-docker-action@master
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: lewiswilkins/array-tomography-tool
